name: branch verify gradle
on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  branch-verify-gradle:
    uses: entur/abt-gha-public/.github/workflows/gradle-open-source-verify.yml@openSource
