name: branch verify maven
on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  branch-verify-maven:
    uses: entur/abt-gha-public/.github/workflows/maven-open-source-verify.yml@openSource
