name: Validate branch
on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  validate-maven-build:
    uses: entur/abt-gha-public/.github/workflows/maven-open-source-verify.yml@openSource
