name: Validate branch
on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  validate-gradle-build:
    uses: entur/abt-gha-public/.github/workflows/validate-jar-gradle-sona.yml@main
