name: Deploy main
on:
  push:
    branches:
      - main

jobs:
  deploy-main-gradle:
    if: "!contains(github.event.head_commit.message, '[skip-release]')"
    uses: entur/gha-maven-central/.github/workflows/gradle-publish.yml@main
    secrets: inherit
    with:
      next_version: patch
      version_strategy: tag
      version_tag_prefix: v

  post-failure-to-slack:
    needs: deploy-main-gradle
    if: failure()
    uses: entur/gha-slack/.github/workflows/post.yml@v2
    with:
      channel_id: ${{ vars.CHANNEL_ID }}
      message: "🔴 Gradle artifact deploy failed for ${{ github.repository }}\n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    secrets: inherit

  post-success-to-slack:
    needs: deploy-main-gradle
    if: success()
    uses: entur/gha-slack/.github/workflows/post.yml@v2
    with:
      channel_id: ${{ vars.CHANNEL_ID}}
      message: "🟢 Gradle artifact deploy success for ${{ github.repository }}\n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    secrets: inherit
