name: Validate, build and deploy tag/release
on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  gradle-build-and-release:
    uses: entur/abt-gha-public/.github/workflows/gradle-open-source-release-current-tag-to-maven-central.yml@openSource
    secrets: inherit
    with:
      tasks: build publishToSonatype
      release-prefix: deploy-tag-gradle-

  post-failure-to-slack:
    needs: gradle-build-and-release
    if: failure()
    uses: entur/gha-slack/.github/workflows/post.yml@v2
    with:
      channel_id: ${{ vars.CHANNEL_ID }}
      message: "🔴 Gradle artifact deploy failed for ${{ github.repository }}\n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    secrets: inherit

  post-success-to-slack:
    needs: gradle-build-and-release
    if: success()
    uses: entur/gha-slack/.github/workflows/post.yml@v2
    with:
      channel_id: ${{ vars.CHANNEL_ID}}
      message: "🟢 Gradle artifact deploy success for ${{ github.repository }}\n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    secrets: inherit

